# Array Manipulation

In [1]:
# importing the numpy library
import numpy as np

In [2]:
# Changing the shape of array:

#reshape()
#ravel(data, order) --- returns a flat array

#np.ravel(array, order)

x = np.arange(15).reshape(3,5)
print("Before using ravel function")
print(x)

print('after applying ravel')
print(x.ravel())

Before using ravel function
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
after applying ravel
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [3]:
# Transposing
#transpose(array, axes)
x = np.arange(12).reshape(3,4)
print(x)
print('array after transposing:')
print(np.transpose(x))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
array after transposing:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [4]:
#ndarray.T
x = np.arange(9).reshape(3,3)
print(x)
print('array after transposing:')
print(x.T)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
array after transposing:
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [5]:
#np.rollaxis(array, axis, start)-- rolls the axis backwards
#axis --- axis to roll backwards
#start --- zero by default.

y = np.arange(12).reshape(2,3,2)
print('array y:')
print(y)

array y:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [7]:
print('array y after applying rollaxis')
print(np.rollaxis(y,2)) #rolls axis 2 to axis 0

array y after applying rollaxis
[[[ 0  2  4]
  [ 6  8 10]]

 [[ 1  3  5]
  [ 7  9 11]]]


In [8]:
print(np.rollaxis(y,2,1))

[[[ 0  2  4]
  [ 1  3  5]]

 [[ 6  8 10]
  [ 7  9 11]]]


In [9]:
#Swapaxes ----> interchanges the axes of an array
#np.swapaxes(array, axis1, axis2)

a = np.arange(8).reshape(2,2,2) 
print(a) 

# now swap numbers between axis 0 (along depth) and axis 1 
#(along width) 
print("array after swapping the axes:")
print(np.swapaxes(a, 1, 0))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
array after swapping the axes:
[[[0 1]
  [4 5]]

 [[2 3]
  [6 7]]]


### Changing dimesnions

In [12]:
#np.broadcast
x = np.array([[1], [2], [3]]) 
y = np.array([4, 5, 6])  
b = np.broadcast(x,y) 
print(b)
print(b.shape)

#np.broadcast_to(array, shape) --- broadcasts an array to a new shape
a = np.arange(4).reshape(1,4) 
print(a)
print(np.broadcast_to(a,(4,4)))

(3, 3)
[[0 1 2 3]]
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [14]:
#squeeze ---removes one-dimensional entry from the shape of the given array
#np.squeeze(array,axis)
x = np.arange(9).reshape(1,3,3) 
print(x)

y = np.squeeze(x)
print(y)

print(x.shape)
print(y.shape)

[[[0 1 2]
  [3 4 5]
  [6 7 8]]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
(1, 3, 3)
(3, 3)


### Joining arrays

In [16]:
#np.concatenate((arr1,arr2...),axis) --- joins sequence of arrays along an axis
a = np.array([[1,2],[3,4]]) 
print(a)  
b = np.array([[5,6],[7,8]])
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [17]:
print(np.concatenate((a,b)))#joining two arrays along axis 0 

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [18]:
print(np.concatenate((a,b),axis = 1)) #joining arrays on axis 1

[[1 2 5 6]
 [3 4 7 8]]


In [19]:
#stack(arrays,axis) --- joins sequence of arrays along a new axis
a = np.array([[1,2],[3,4]]) 
print(a) 
b = np.array([[5,6],[7,8]])  
print(b) 
print('Stacking two arrays along axis 0:') 
print(np.stack((a,b),0))  
print('Stacking two arrays along axis 1:') 
print(np.stack((a,b),1))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
Stacking two arrays along axis 0:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Stacking two arrays along axis 1:
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [20]:
#hstack --- stacks arrays horizontally
a = np.array([[1,2],[3,4]]) 
print(a) 
b = np.array([[5,6],[7,8]]) 
print(b)
c = np.hstack((a,b)) 
print('hstack:')
print(c)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
hstack:
[[1 2 5 6]
 [3 4 7 8]]


In [21]:
#vstack --- stacks arrays vertically
c = np.vstack((a,b))
print('vstack:')
print(c)

vstack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Splitting arrays

In [22]:

#np.split(array,indices,axis) --- splits an array into multiple sub arrays
a = np.arange(9) 
print(a) 
print('Splitting the array in 3 equal-sized subarrays:') 
b = np.split(a,3) 
print(b)

[0 1 2 3 4 5 6 7 8]
Splitting the array in 3 equal-sized subarrays:
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [23]:
print('Split the array at positions indicated in 1-D array:') 
c = np.split(a,[4,7])
print(c) 

Split the array at positions indicated in 1-D array:
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [24]:
#hsplit
a = np.arange(16).reshape(4,4) 
print(a) 
print('Horizontal splitting:') 
b = np.hsplit(a,2) 
print(b)

#vsplit
print('Vertical splitting:') 
b = np.vsplit(a,2) 
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Horizontal splitting:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
Vertical splitting:
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


### Adding and Removing elements

In [25]:
##resize --- returns a new array with specified shape
a = np.array([[1,2,3],[4,5,6]]) 
print(a) 
print(a.shape) 

b = np.resize(a, (3,2)) 
print(b)  
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [26]:
# Observe that the first row of a is repeated in b since the size is bigger 
print('Resizing the second array:') 
b = np.resize(a,(3,3)) 
print(b)

Resizing the second array:
[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [27]:
# append(array,values/elements,axis) --- appends the values to the end of array
a = np.array([[1,2,3],[4,5,6]]) 
print(a) 
print('append elements to array:') 
print(np.append(a, [7,8,9])) 
  
print('append elements along axis 0:') 
print(np.append(a, [[7,8,9]],axis = 0)) 
  
print('append elements along axis 1:') 
print(np.append(a, [[5,5,5],[7,8,9]],axis = 1))

[[1 2 3]
 [4 5 6]]
append elements to array:
[1 2 3 4 5 6 7 8 9]
append elements along axis 0:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
append elements along axis 1:
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [28]:
##insert(array,obj,value,axis) --- inserts the values along a given axis
#obj -- The index before which insertion is to be made
a = np.array([[1,2],[3,4],[5,6]]) 
print(a) 
  
print('Axis parameter not passed so the input array is flattened before insertion')
print(np.insert(a,3,[11,12])) 
 
print('Axis parameter passed. The values array is broadcast to match input array')
print('Broadcast along axis 0:') 
print(np.insert(a,1,[11],axis = 0)) 
 
print('Broadcast along axis 1:') 
print(np.insert(a,1,11,axis = 1))


[[1 2]
 [3 4]
 [5 6]]
Axis parameter not passed so the input array is flattened before insertion
[ 1  2  3 11 12  4  5  6]
Axis parameter passed. The values array is broadcast to match input array
Broadcast along axis 0:
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]
Broadcast along axis 1:
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


In [29]:
##np.delete(array,obj,axis)
#obj -- can be a slice, integer or array of integers
a = np.arange(12).reshape(3,4) 
print(a) 
print(np.delete(a,5)) 
  
print('Column 2 deleted:')  
print(np.delete(a,1,axis = 1)) 


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  6  7  8  9 10 11]
Column 2 deleted:
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


In [31]:
##np.unique(arr, return_index, return_inverse, return_counts)
a = np.array([5,2,6,2,7,5,6,8,2,9]) 
print(a) 
print('Unique values of array a:') 
u = np.unique(a) 
print(u)   



[5 2 6 2 7 5 6 8 2 9]
Unique values of array a:
[2 5 6 7 8 9]


In [32]:
print('Unique array and Indices array:') 
u,indices = np.unique(a, return_index = True) 
print(indices)

Unique array and Indices array:
[1 0 2 4 7 9]


In [33]:
print('Indices of unique array:') 
u,indices = np.unique(a,return_inverse = True) 
print(u)  

print('Indices are:') 
print(indices) 

print('reconstructing the original array using indices:') 
print(u[indices])

print('return the count of repetitions of unique elements:') 
u,indices = np.unique(a,return_counts = True) 
print(u) 
print(indices)


Indices of unique array:
[2 5 6 7 8 9]
Indices are:
[1 0 2 0 3 1 2 4 0 5]
reconstructing the original array using indices:
[5 2 6 2 7 5 6 8 2 9]
return the count of repetitions of unique elements:
[2 5 6 7 8 9]
[3 2 2 1 1 1]


### String Functions

In [35]:
#add() --- returns element wise string concatenation of two arrays
x = np.char.add(['Hello! '],['Welcome to Numpy'])
print(x)

['Hello! Welcome to Numpy']


In [36]:
#multiply() --- returns multiple concatenation
print(np.char.multiply('Numpy ',3))

Numpy Numpy Numpy 


In [37]:
#center() ---> returns an array of the required width so that the input string
      #is centered and padded on the left and right with fillchar
# np.char.center(arr, width,fillchar) 
print(np.char.center('Numpy', 10,fillchar = '*'))


**Numpy***


In [38]:
#upper()
print(np.char.upper('hi')) 
print(np.char.upper(['hello','numpy']))

#lower()
print(np.char.lower('HI')) 
print(np.char.lower(['HELLO','NUMPY']))

#capitalize()
print(np.char.capitalize('hi')) 
print(np.char.capitalize(['hello','numpy']))

HI
['HELLO' 'NUMPY']
hi
['hello' 'numpy']
Hi
['Hello' 'Numpy']


In [39]:
#split()
print(np.char.split('hello how are you?')) 
print(np.char.split('BawarchiBiryani,Rtc X Roads,Hyderabad', sep = ','))

#splitline() --- returns a list of elements in the array, breaking at line boundaries
print(np.char.splitlines('hello\nhow are you?')) 

#strip()
print(np.char.strip('ameerpet','a')) 

['hello', 'how', 'are', 'you?']
['BawarchiBiryani', 'Rtc X Roads', 'Hyderabad']
['hello', 'how are you?']
meerpet


In [40]:
#join() --- returns a string in which the individual characters are
            #joined by separator character specified.

print(np.char.join(':','dmy')) 
print(np.char.join(['/','-'],['dmy','ymd']))

#replace()
print(np.char.replace("I'm learning Data Science", "I'm", "We're"))


d:m:y
['d/m/y' 'y-m-d']
We're learning Data Science


### Arithmetic operations

In [42]:
#np.add()
a = np.arange(9).reshape(3,3) 
print(a)
b = np.array([10,20,30]) 
print(b)
print("array after adding:")
print(np.add(a,b))

#np.subtract()
print("array after subtracting:")
print(np.subtract(b,a))

#np.multiply()
print("array after multiplying:")
print(np.multiply(a,b))


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[10 20 30]
array after adding:
[[10 21 32]
 [13 24 35]
 [16 27 38]]
array after subtracting:
[[10 19 28]
 [ 7 16 25]
 [ 4 13 22]]
array after multiplying:
[[  0  20  60]
 [ 30  80 150]
 [ 60 140 240]]


In [43]:
#np.divide()
print("array after dividing:")
print(np.divide(a,b))


#np.power()
a = np.array([10,100,1000]) 
print(a) 
print('array after applying power function')
print(np.power(a,2)) 


#np.mod()
a = np.array([10,20,30]) 
b = np.array([3,5,7]) 

print(a) 
print(b) 
print('array after applying mod function:') 
print(np.mod(a,b)) 


array after dividing:
[[0.         0.05       0.06666667]
 [0.3        0.2        0.16666667]
 [0.6        0.35       0.26666667]]
[  10  100 1000]
array after applying power function
[    100   10000 1000000]
[10 20 30]
[3 5 7]
array after applying mod function:
[1 0 2]


### Statistical functions

In [44]:
#np.amin()
x = np.array([[3,7,5],[8,4,3],[2,4,9]]) 
print(x)
print(np.amin(x))
print('amin() value along axis 1:') 
print(np.amin(x,1)) 
print('amin() value along axis 0:') 
print(np.amin(x,0)) 

[[3 7 5]
 [8 4 3]
 [2 4 9]]
2
amin() value along axis 1:
[3 3 2]
amin() value along axis 0:
[2 4 3]


In [45]:
#np.amax()  
print('value of amax():') 
print(np.amax(x)) 

print('amax() value along axis 0:') 
print(np.amax(x, axis = 0))

value of amax():
9
amax() value along axis 0:
[8 7 9]


In [46]:
#np.ptp() ---> range [max - min]
print('ptp value:')
print(np.ptp(x))

ptp value:
7


In [47]:
#np.percentile(array,p,axis)
#p --> percentile value between 0 to 100
print('percentile values')
print(np.percentile(x,50)) #computes 50th percentile
print(np.percentile(x,100)) #computes 100th percentile


percentile values
4.0
9.0


In [49]:
#np.mean()
print('mean values are:')
print(np.mean(x))
print(np.mean(x,axis=0))
print(np.mean(x,axis=1))

#np.median()
print('median values are:')
print(np.median(x))
print(np.median(x,axis=0))
print(np.median(x,axis=1))

#np.average()
print('average values are:')
print(np.average(x))
print(np.average(x,axis=0))
print(np.average(x,axis=1))

#np.std()
print('std values are:')
print(np.std(x))
print(np.std(x,axis=0))
print(np.std(x,axis=1))

#np.var()
print('variance values are:')
print(np.var(x))
print(np.var(x,axis=0))
print(np.var(x,axis=1))


mean values are:
5.0
[4.33333333 5.         5.66666667]
[5. 5. 5.]
median values are:
4.0
[3. 4. 5.]
[5. 4. 4.]
average values are:
5.0
[4.33333333 5.         5.66666667]
[5. 5. 5.]
std values are:
2.309401076758503
[2.62466929 1.41421356 2.49443826]
[1.63299316 2.1602469  2.94392029]
variance values are:
5.333333333333333
[6.88888889 2.         6.22222222]
[2.66666667 4.66666667 8.66666667]


In [50]:
#np.sort ---> returns sorted values of the input array
#np.sort(array, axis, order)
a = np.array([[3,7],[9,1]]) 
print(a) 
print('after applying sort function:') 
print(np.sort(a)) 
print('Sorting along axis 0:') 
print(np.sort(a, axis = 0))

[[3 7]
 [9 1]]
after applying sort function:
[[3 7]
 [1 9]]
Sorting along axis 0:
[[3 1]
 [9 7]]


In [51]:
# Order parameter in sort function 
dt = np.dtype([('name', 'S10'),('age', int)]) 
x = np.array([("Ram",23),("Robert",25),("Rahim",27)], dtype = dt) 
print(x) 
print('Order by name:') 
print(np.sort(x, order = 'name'))

[(b'Ram', 23) (b'Robert', 25) (b'Rahim', 27)]
Order by name:
[(b'Rahim', 27) (b'Ram', 23) (b'Robert', 25)]


In [52]:
#np.nonzero() ---> returns the indices of non-zero elements
b = np.array([[30,40,0],[0,20,10],[50,0,60]]) 
print('array b is:')
print(b)
print('after applying nonzero() function:') 
print(np.nonzero(b))

array b is:
[[30 40  0]
 [ 0 20 10]
 [50  0 60]]
after applying nonzero() function:
(array([0, 0, 1, 1, 2, 2], dtype=int64), array([0, 1, 1, 2, 0, 2], dtype=int64))


In [53]:
#np.where() ---> returns the indices of elements when the condition is satisfied.
x = np.arange(12).reshape(3,4) 
print(x)  
print('Indices of elements > 3') 
y = np.where(x > 3) 
print(y)  

print('Use these indices to get elements satisfying the condition') 
print(x[y])


#np.extract() ---> returns the elements satisfying any condition.
x = np.arange(9).reshape(3,3) 
print(x)  

# define a condition 
condition = np.mod(x,2) == 0 

print('element-wise value of condition') 
print(condition)  

print('extract elements using condition') 
print(np.extract(condition, x))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Indices of elements > 3
(array([1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))
Use these indices to get elements satisfying the condition
[ 4  5  6  7  8  9 10 11]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
element-wise value of condition
[[ True False  True]
 [False  True False]
 [ True False  True]]
extract elements using condition
[0 2 4 6 8]


### Linear Algebra

In [55]:
#NumPy package contains numpy.linalg module that provides all the 
#functionality required for linear algebra.

#dot()--- returns dot product of two arrays
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
print('dot product is:')
print(np.dot(a,b))


##vdot() --- returns dot product of two vectors
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
print('vector dot product is:')
print(np.vdot(a,b))

dot product is:
[[37 40]
 [85 92]]
vector dot product is:
130


In [56]:
##inner() ---- returns inner product of two arrays
a = np.array([[1,2], [3,4]]) 
print(a) 
b = np.array([[11, 12], [13, 14]]) 
print(b)
print('inner product is:')
print(np.inner(a,b))

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]
inner product is:
[[35 41]
 [81 95]]


In [57]:
##matmul() ---- returns matrix product of two arrays
import numpy.matlib 
a = [[1,0],[0,1]] 
b = [[4,1],[2,2]] 
print('matrix product is:')
print(np.matmul(a,b))

a = [[1,0],[0,1]] 
b = [1,2] 
print(np.matmul(a,b)) 
print(np.matmul(b,a))

a = np.arange(8).reshape(2,2,2) 
b = np.arange(4).reshape(2,2) 
print(np.matmul(a,b))


matrix product is:
[[4 1]
 [2 2]]
[1 2]
[1 2]
[[[ 2  3]
  [ 6 11]]

 [[10 19]
  [14 27]]]


In [58]:

##determinant() ---- computes the determinant of an array
a = np.array([[1,2], [3,4]]) 
print(np.linalg.det(a))

b = np.array([[6,1,1], [4, -2, 5], [2,8,7]]) 
print(np.linalg.det(b)) 


##inv() ---- finds the inverse of the matrix
x = np.array([[1,2],[3,4]]) 
y = np.linalg.inv(x) 
print(x) 
print(y) 

-2.0000000000000004
-306.0
[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [59]:
# Matrix library
#NumPy package contains a Matrix library numpy.matlib. 
#This module has functions that return matrices instead of ndarray objects.

import numpy.matlib

#np.matlib.empty(shape,dtype,order)
print(np.matlib.empty((2,2)))


#np.matlib.zeros()
print(np.matlib.zeros((2,2))) 


#np.matlib.ones()
print(np.matlib.ones((2,2))) 


#np.matlib.eye(n,M,k,dtype) --- returns a matrix with 1 along the diagonal elements and the zeros elsewhere.
#n--rows,M--columns, k--index of diagonal element
print(np.matlib.eye(n = 3, M = 4, k = 0, dtype = int))


#np.matlib.identity()
print(np.matlib.identity(5, dtype = int))


#np.matlib.rand()
print(np.matlib.rand(3,2))

[[2.  1. ]
 [1.5 0.5]]
[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[0.27201696 0.43940998]
 [0.45829579 0.45652134]
 [0.00867043 0.33063545]]
