In [17]:
import numpy as np

In [18]:
## integer array indexing:

a = np.array([[1,2], [3,4], [5,6]])
print(a)


[[1 2]
 [3 4]
 [5 6]]


In [19]:
b = a[[0,1,2],[0,1,1]]
print(b)

[1 4 6]


* The above index selection includes items at positions (0,0), (1,1) and (2,1)

In [20]:
x = np.array([[1,2,3], [4, 5, 6], [10, 11, 12], [0, 9, 8]])
print(x)


[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]
 [ 0  9  8]]


In [21]:
rows = np.array([[0, 0], [2, 2]])
cols = np.array([[2, 0], [0, 2]])

y = x[rows, cols]
print(y)


[[ 3  1]
 [10 12]]


## Slicing

x = [1,2,3,4,5,6,7,8]
s = x[start:stop:step]
* start --> starting index
* stop  --> last index (excluded)
* step  --> number of steps

In [22]:
# slicing
z = x[1:4, 1:3]
print(z)


[[ 5  6]
 [11 12]
 [ 9  8]]


In [23]:
y = x[1:3,[1,2]]
print(y)

[[ 5  6]
 [11 12]]


## Boolean indexing

In Boolean array indexing, the resultant array object is due to the 
result of a boolean expression

In [24]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [25]:
# in this example items greater than 5 are selected as a result of boolean indexing.

print(x[x>5])

[ 6  7  8  9 10 11 12]


In [26]:
# selecting all items less than 10
print(x[x < 10])

[1 2 3 4 5 6 7 8 9]


In [34]:
# selecting all items except 8 

print(x[x!=8])

[ 1  2  3  4  5  6  7  9 10 11 12]


In [28]:
# selecting even items
print(x[x%2 == 0])

[ 2  4  6  8 10 12]


In [29]:
# selecting odd items
print(x[x%2 != 0])

[ 1  3  5  7  9 11]
