In [2]:
# importing the numpy library
import numpy as np

In [3]:
# creating a rank 1 (one dimension) array:
x = np.array([1,2,3,4,5,6])

# displaying the array
print(x)

[1 2 3 4 5 6]


In [4]:
# checking the datatype
print(x.dtype)

int32


In [5]:
type(x)

numpy.ndarray

In [6]:
# checking the shape of array object
x.shape

(6,)

In [7]:
# size of array
x.size

6

In [9]:
# checking the number of dimensions
x.ndim

1

In [10]:
# Indexing (accessing the array elements)
print(x[0])
print(x[-1])
print(x[1],x[3])


1
6
2 4


In [15]:
# creating multi dimensional array
y = np.array([(1,2,3), (4,5,6)])
w = np.array([[4,5,6], [7,8,9], [0,2,3]])
print(y, end='\n\n')
print(w)

[[1 2 3]
 [4 5 6]]

[[4 5 6]
 [7 8 9]
 [0 2 3]]


In [16]:
print(y.ndim)
print(w.ndim)

2
2


In [17]:
# size
print(y.size)
print(w.size)

# shape
print(y.shape)
print(w.shape)


6
9
(2, 3)
(3, 3)


In [18]:
# creating an array with different datatype

# creating array of int datatype:
a = np.array([1,2,3], dtype = int)
print(a)


[1 2 3]


In [19]:
# creating array of float datatype:
b = np.array([1,2,3], dtype = float)
print(b)


[1. 2. 3.]


In [20]:
# creating array of complex datatype:
c = np.array([1,2,3], dtype = complex)
print(c)


[1.+0.j 2.+0.j 3.+0.j]


Even you have the functionality of creating a structured data type and
apply it to a ndarray object. This type of data type is also called 
Structured data type.

Let's see a use case below:

In [22]:
# Creating a Structured data type:
dt_1 = np.dtype([('age', np.int8)])
print(dt_1)


[('age', 'i1')]


In [23]:
# applying above datatype to an ndarray object:
a = np.array([(25,), (28,), (30,)], dtype = dt_1)
print(a)


[(25,) (28,) (30,)]


In [24]:
# accessing the values present in age column:
print(a['age'])

[25 28 30]


In [25]:
# creating an array with user defined data type:

#first create a user defined data type:
emp = np.dtype([('eno', 'i4'), ('ename', 'S20'), ('age', 'i4'), ('loc', 'S20')])

# applying the datatype to an array object:
Employees = np.array([(101, 'snigdha', 25, 'sambhal'),
                     (102, 'sneha', 23, 'Meerut'),
                     (103, 'Kousik', 26, 'Bangalore'),
                     (104, 'Aravind', 27, 'Hyderabad'),
                     (105, 'Kiran', 30, 'Chennai'),
                     (106, 'Abdul', 30, 'Mumbai')])

# displaying the array:
print(Employees)


[['101' 'snigdha' '25' 'sambhal']
 ['102' 'sneha' '23' 'Meerut']
 ['103' 'Kousik' '26' 'Bangalore']
 ['104' 'Aravind' '27' 'Hyderabad']
 ['105' 'Kiran' '30' 'Chennai']
 ['106' 'Abdul' '30' 'Mumbai']]


In [ ]:
Note: Each built-in data types has a unique single character code:
        b ----> boolean
        i ----> ineger
        f ----> float
        S ----> String
        c ----> complex 
        M ----> datetime